Vagrant.configure("2") do |config|
  config.vm.box = "MaxPeal/alpine-clean"
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.ssh.shell = "/bin/sh -l"
#  config.ssh.sudo_command = "su -l root -c '%c'"
  #config.ssh.disable_sudo = "true"
  #config.ssh.sudo_command = "/bin/sh -c %c"
  #org config.ssh.sudo_command = "sudo -E -H %c"
#  config.vm.provision "shell",
#    privileged: "true",
#    inline: "echo Hello, World"
#  if Vagrant.has_plugin?("vagrant-proxyconf")
#    config.proxy.http     = "http://192.168.0.2:3128/"
#    config.proxy.https    = "http://192.168.0.2:3128/"
#    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
#    config.proxy.disable_sudo = "true"
#  end
end
